Allow views to be overridden with vendor content
SUSE-Enceladus/blue-horizon pull request #173
Opened 2020-11-10 00:41 UTC by bear454

... and set up the Plan view to be friendly for this.

2020-11-10 00:41 UTC, bear454 commented
CC @stefanotorresi

2020-11-11 13:01 UTC, stefanotorresi requested changes

2020-11-11 15:42 UTC, bear454 commented on app/views/plans/show.html.haml
> +    = render('plans/plan', plan: @plan) if @plan.present?
Resolved in 4f64e56 .

2020-11-11 15:42 UTC, bear454 commented on spec/features/plan_spec.rb
> +      expect(page).not_to have_selector('code.output')
Resolved in 4f64e56.

2020-11-11 15:48 UTC, stefanotorresi approved these changes
perfect, @bear454! :+1: Thanks a lot :beers:

2020-11-11 15:49 UTC, merged