Feature/markdown html tags
SUSE-Enceladus/blue-horizon pull request #175
Opened 2020-11-11 12:34 UTC by arbulu89

Disable html filtering in the markdown render process.

Besides that, I have added an empty vendor stylesheet to use from the vendor folder without modifying the `application.css` file. I don't know if there is a better option, but I have not found it.

This allows markdown entries with html tags. 
Example:
![collapsable](https://user-images.githubusercontent.com/36370954/98812094-2ac56680-2422-11eb-973c-267affe738ce.gif)

2020-11-11 15:16 UTC, bear454 commented on .gitignore
> +!vendor/assets/stylesheets/vendor_custom.css
I'll make a change internally of `/home/jmason/projects/blue-horizon/app/assets/stylesheets/custom.scss` to `overrides.scss`... then we can import `custom.(s)css`.

2020-11-11 15:22 UTC, bear454 commented on .gitignore
> +!vendor/assets/stylesheets/vendor_custom.css
Done in 9dd0738.

2020-11-11 15:25 UTC, bear454 requested changes
Sorry for the namespace conflict; please use `custom.(s)css` - no more need for the `vendor_` prefix.

One nitpick - the PR description doesn't describe the bulk of the PR; please update the description so the merge comment makes sense, and next time please separate this type of change into two PRs.

2020-11-12 07:56 UTC, arbulu89 commented on .gitignore
> +!vendor/assets/stylesheets/vendor_custom.css
@bear454 But this is not going to work out of the box. I would still need to change the `application.css` to require `custom.css`. The whole idea was to avoid that change. Otherwise in our project we will need to change this file that is outside the `vendor` folder.
Or do you just mean that I should rename `vendor_custom.css` by `custom.css`?

2020-11-13 08:34 UTC, arbulu89 commented
Hi @bear454, 
I have removed the 2nd commit and moved this logic to: https://github.com/SUSE-Enceladus/blue-horizon/pull/177

2020-11-13 16:12 UTC, bear454 approved these changes

2020-11-13 16:12 UTC, merged