Enable custom.css styles usage
SUSE-Enceladus/blue-horizon pull request #177
Opened 2020-11-12 09:13 UTC by arbulu89

Follow up of https://github.com/SUSE-Enceladus/blue-horizon/pull/175

This PR implements the option to use `custom.[s]css` style files to customize the application.

2020-11-13 16:23 UTC, bear454 requested changes

2020-11-13 16:23 UTC, bear454 commented on .gitignore
> +!vendor/assets/stylesheets/custom.scss
We shouldn't include the file - for any other project this will be owned by the config package, and not the blue-horizon package. Just add a .keep file for the dir instead (until I can build a generator for the vendor architecture).

2020-11-13 17:30 UTC, arbulu89 commented on .gitignore
> +!vendor/assets/stylesheets/custom.scss
The issue is that if I don't have this file, we cannot have the `require custom` in the `application.css`, rails fails.
![image](https://user-images.githubusercontent.com/36370954/99102386-4b3a2000-25de-11eb-9274-7b0b57d66207.png)

So, basically, I cannot add custom styles without touching a file in the `app` folder

2020-11-16 07:47 UTC, arbulu89 commented
Superseded by https://github.com/SUSE-Enceladus/blue-horizon/pull/180

2020-11-16 07:47 UTC, closed without merging