Correct password show/hide icon usage to use correct styles
SUSE-Enceladus/blue-horizon pull request #185
Opened 2020-12-02 07:58 UTC by arbulu89

Correct password show/hide usage as recommend in the EOS branding:
https://suse.eosdesignsystem.com/form-elements/input-fields

New:
![peek-unpeek](https://user-images.githubusercontent.com/36370954/100844525-439ec600-347c-11eb-80a4-bee5618537cf.gif)

Before:
![image](https://user-images.githubusercontent.com/36370954/100844599-5d400d80-347c-11eb-8c8a-0348623f6aef.png)

2020-12-02 08:03 UTC, stefanotorresi approved these changes
Nice! Just a small nitpick.

2020-12-02 08:03 UTC, stefanotorresi commented on app/assets/javascripts/variables.js
> +    group.find("div.peek").show();
Nitpick: I think we can remove the div tag altogether from these CSS selectors and just use the classes.

2020-12-07 20:16 UTC, bear454 requested changes

2020-12-07 20:16 UTC, bear454 commented on app/assets/stylesheets/override.scss
> +.input-group-append {
This will have unanticipated side effects on other form elements; please isolate it to the .peek / .unpeek classes.

2020-12-09 10:29 UTC, arbulu89 commented
@bear454 Styles file changed.
I have added the specific `div`s too, as we might find other `peek/unpeek` elements in other places, like in our specific plan page.
https://github.com/SUSE/blue-horizon/blob/sap-azure/vendor/views/plans/_plan.haml#L20

2020-12-09 16:00 UTC, bear454 approved these changes

2020-12-09 16:00 UTC, merged